name: Android CI

on: [push]

jobs:

  android-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: android-ci-github-action
      uses: Code0987/android-ci-github-action@v0.1.0

      with:
        args: |
          npm install
          export GRADLE_USER_HOME=`pwd`./.gradle
          chmod 755 ./gradlew 
          ./gradlew -p ./ check
          
    - name: Upload lint output
      uses: actions/upload-artifact@v1
      with:
        name: lint_output.html
        path: /github/workspace/app/build/reports/lint-results.html
      
    - name: Download file with actions
      uses: actions/download-artifact@v2
      with:
        name: actions-output-file

