name: Android CI

on: [push]

jobs:

  android-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: android-ci-github-action
      uses: Code0987/android-ci-github-action@v0.1.0

      with:
        args: |
          npm install
          export GRADLE_USER_HOME=`pwd`./src/.gradle
          chmod 755 ./src/gradlew 
          ./src/gradlew -p ./src check
